import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { Menu } from "lucide-react";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-950 flex flex-col min-h-screen`}
    >
      <header className="flex justify-between px-10 mt-2 mx-4  pt-2 text-[100%] text-white  ">
  <h1 className="text-2xl font-bold ">Saim</h1>
    <nav className="flex space-x-6 md:space-x-10 items-center">
      <div className="md:hidden mx-auto mt-1">
        <Sheet>  
  <SheetTrigger> <Menu/>
  </SheetTrigger>
  <SheetContent className="bg-gray-950 w-[250px]px-6 py-10 "> 
    <SheetHeader>
      <SheetTitle className="text-2xl text-center text-white mb-8 ">Navigation</SheetTitle>
         <div className="flex flex-col bg-gray-950 items-center justify-center translate-y-10 text-white text-base space-y-6">
    <Link href="/" className="hover:text-green-300">Home</Link>
    <Link href="/about"className="hover:text-green-300">About</Link>
    <Link href={"/projects"}className="hover:text-green-300">Projects</Link>
    <Link href={"/Contact"}className="hover:text-green-300">Contact</Link>
      </div>
  
    </SheetHeader>
  </SheetContent>
</Sheet>

      </div>
      <div className="hidden md:flex space-x-8 ">
    <Link href="/" className="hover:text-green-300">Home</Link>
    <Link href="/about"className="hover:text-green-300">About</Link>
    <Link href={"/projects"}className="hover:text-green-300">Projects</Link>
    <Link href={"/Contact"}className="hover:text-green-300">Contact</Link>
      </div>
    </nav>
</header>
  <main className="flex-grow">
        {children}
    </main>  
        <footer className=" text-gray-500 text-md text-center mb-2">
  © 2025 Saim. All rights reserved.

  <div className="flex justify-center gap-x-2 mt-2">


<Link href={"https://github.com/saimnomann"} target="_blank">
<Image src="/gitub_new.png" alt="github" width={25} height={30} className=" object-contain h-7 w-[100%] items-end" /></Link>
<Link href={"https://www.linkedin.com/in/muhammad-saim-noman-2823212a3/"} target="_blank">
<Image src={"/linkedin.png"} width={25} height={30} alt="/linkedin.png" className="object-contain h-10 w-[120%] items-center pb-2 "/></Link>
  </div>

      </footer>
      </body>
    </html>
  );
}
